version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
  build:
    commands:
      - SRC_DIR=$(pwd)
      - cd lambda
      - echo "Zipping Lambda source..."
      - zip -r lambda.zip app.js
artifacts:
  files:
    - lambda.zip
  discard-paths: yes