version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
  build:
    commands:
      - echo "Zipping Lambda source..."
      - cd lambda
      - zip -r ../lambda.zip app.js   # create in root
artifacts:
  files:
    - lambda.zip
  discard-paths: yes
