AWSTemplateFormatVersion: '2010-09-09'
Description: CodeBuild project for packaging Lambda

Parameters:
  ProjectName:
    Type: String
  DeploymentBucket:
    Type: String
  CodeBuildServiceRoleArn:
    Type: String

Resources:
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub "${ProjectName}-Lambda-Build"
      ServiceRole: !Ref CodeBuildServiceRoleArn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:7.0
        Type: LINUX_CONTAINER
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec.yml
      TimeoutInMinutes: 10

Outputs:
  CodeBuildProjectName:
    Value: !Ref CodeBuildProject